# Site settings
title: HiCol.in
email: Sup@HiCol.in
description: > # this means to ignore newlines until "baseurl:"
  Recapturing the hustle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hicol.in" # the base hostname & protocol for your site
twitter_username: colinmcgrath
github_username:  colinmcgrath

# Build settings
markdown: kramdown
